server:
  port: 8000
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lafinboard?serverTimezone=Asia/Seoul
    username: lafin
    password: lafin716!@
  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl